language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

addons:
  chrome: stable

before_install: 
  - pip install --upgrade pip

install:
  - python setup.py install

script: tox -e ${TOXENV}