language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

addons:
  chrome: stable

install:
  - pip install -r requirements_dev.txt
  - python setup.py install

script: tox -e ${TOXENV}