language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

addons:
  chrome: stable

before_install:
  - wget -N http://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

install:
  - pip install -r requirements_dev.txt
  - python setup.py install

script: tox -e ${TOXENV}